/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sz_jvm_NativeMethod */

#ifndef _Included_com_sz_jvm_NativeMethod
#define _Included_com_sz_jvm_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sz_jvm_NativeMethod
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sz_jvm_NativeMethod_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
