/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sz_jvm_NativeMethod */

#ifndef _Included_com_sz_jvm_NativeMethod
#define _Included_com_sz_jvm_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sz_jvm_NativeMethod
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sz_jvm_NativeMethod_hello
  (JNIEnv *, jclass);

/*
 * Class:     com_sz_jvm_NativeMethod
 * Method:    world
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sz_jvm_NativeMethod_world
  (JNIEnv *, jobject);

/*
 * Class:     com_sz_jvm_NativeMethod
 * Method:    field
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sz_jvm_NativeMethod_field
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
