/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sz_jvm_JavaThread */

#ifndef _Included_com_sz_jvm_JavaThread
#define _Included_com_sz_jvm_JavaThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sz_jvm_JavaThread
 * Method:    start0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sz_jvm_JavaThread_start0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
